### ISSUE TITLE
Shall I share my Dockerfile?

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-docker#1]
Hello, I've already created an MNE `Dockerfile` that also starts Xvfb to allow for 3d rendering. Shall I just dump that here? Or what is the intended procedure for this repo?

Best wishes!

**Comment by agramfort** [comment]
coordinate with @SherazKhan

>

**Comment by SherazKhan** [comment]
@hoechenberger I think we need to have two types of dockers, one a base image for cloud distributed computing and the second for the interactive work inherited from `Jupyter notebook` image with `Xvfb `binding.

We can also offer a third type of docker image with `freesurfer `and `MNE-C`.

Please contribute your docker, we can follow, [dask-docker](https://github.com/dask/dask-docker) repository structure

**Comment by SherazKhan** [comment]
@hoechenberger @agramfort please guide me in setting up GitHub actions for CI

**Comment by agramfort** [comment]
maybe start with https://github.com/marketplace/actions/build-and-push-docker-images ?

**Comment by hoechenberger** [comment]
> @hoechenberger I think we need to have two types of dockers, one a base image for cloud distributed computing and the second for the interactive work inherited from `Jupyter notebook` image with `Xvfb `binding.

I will make a "base" image **with** Xvfb so you can get 3D rendering e.g. for inclusion in reports (this one is almost ready), and then we can offer another one which builds upon the first one and simply adds the Jupiter server. Not entirely sure if it will be worth the effort providing two separate images, though, but let's see how things go.

> We can also offer a third type of docker image with `freesurfer `and `MNE-C`.

FS integration is actually quite an interesting question, because I'd want to have FS run in a separate container. We'd need to see how we can pass data between those. But that's a detail for later.


> @hoechenberger @agramfort please guide me in setting up GitHub actions for CI

Do you want CI or do you want continuous deployment..?
For the latter, see @agramfort's comment

For the former, I don't see the need at this stage :)

**Comment by SherazKhan** [comment]
> I will make a "base" image with Xvfb so you can get 3D rendering e.g. for inclusion in reports (this one is almost ready), and then we can offer another one which builds upon the first one and simply adds the Jupiter server. Not entirely sure if it will be worth the effort providing two separate images, though, but let's see how things go.

@hoechenberger @agramfort I think, the Docker base image intended for scheduler and workers should be as light as possible to reduce startup time when starting new cloud clusters. 

> FS integration is actually quite an interesting question, because I'd want to have FS run in a separate container. We'd need to see how we can pass data between those. But that's a detail for later.

Agree!

> Do you want CI or do you want continuous deployment?
Both CI and CD, for CD I will try @agramfort suggestion, 

Since we want to update Dockerfile with every mne release, I was wondering if there is any way to set up a testing environment for the Docker images?

**Comment by rob-luke** [comment]
Hi @hoechenberger I would love to see your docker file that has 3d rendering capabilities. No worries if its messy, warts and all, I can help clean it up.

I have a public webinar coming up and was hoping that I could get a docker image up and running to easily onboard people during the talk.

**Comment by larsoner** [comment]
There should be 3D capabilities in this now in the `-plot` variant but @hoechenberger feel free to share your dockerfile at some point!

Would be cool to deduplicate efforts here and https://github.com/mne-tools/mne-python/pull/12306 if relevant as well
